name: weather_nearby
description: "Show weather in your city"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  logger: ^2.2.0
  get: ^4.6.6
  get_it: ^7.7.0
  get_storage: ^2.1.1
  flutter_bloc: ^8.1.5
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  sprintf: ^7.0.0
  unlimited_things_dart: ^0.0.1
  url_strategy: ^0.2.0


dev_dependencies:
  build_runner: ^2.4.9
  dart_code_metrics: ^5.7.6
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/locale/
