/// Generated by LocaleKeysGenerator on 2024-05-19 02:37:31.749947Z
mixin TranslationsKeys {
  /// translation have interpolations: %s
  static const feelLike = 'feel_like';

  static const langRu = 'lang.ru';
  static const langEn = 'lang.en';
  static const now = 'now';
  static const or = 'or';
  static const city = 'city';
  static const shortTimeDay = 'short_time.day';

  /// translation have interpolations: %s
  static const shortTimeHour = 'short_time.hour';

  /// translation have interpolations: %s
  static const shortTimeMinute = 'short_time.minute';

  /// translation have interpolations: %s
  static const shortTimeSeconds = 'short_time.seconds';

  static const shortTimeAgo = 'short_time.ago';

  /// translation have interpolations: %s
  static const shortTimeLastUpdated = 'short_time.last_updated';

  static const weatherValueWindLabel = 'weather_value.wind.label';
  static const weatherValueWindMeasurements = 'weather_value.wind.measurements';
  static const weatherValueHumidityLabel = 'weather_value.humidity.label';
  static const weatherValueHumidityMeasurements =
      'weather_value.humidity.measurements';
  static const weatherValuePressureLabel = 'weather_value.pressure.label';
  static const weatherValuePressureMeasurements =
      'weather_value.pressure.measurements';

  /// translation have interpolations: %s
  static const loadWeatherError = 'load_weather.error';

  static const loadWeatherSolution1 = 'load_weather.solution1';
  static const loadWeatherSolution2 = 'load_weather.solution2';
  static const citiesOptions = 'cities_options';
}
