/// Generated by LocaleKeysGenerator on 2024-05-18 16:29:55.991721Z
mixin TranslationsKeys {
  /// translation have interpolations: %s
  static const feelLike = 'feel_like';

  static const langRu = 'lang.ru';
  static const langEn = 'lang.en';
  static const now = 'now';
}
